url: https://imgiainfo.com
baseurl: ""

# Site settings
title: (img) Imgage - (ia) Intelligence artificielle - (info) Information
email: info@imgiainfo.com
description: "Artiste et codeur passionné, j'explore et développe des projets mêlant intelligence artificielle, art visuel et informatique.

Je propose une gamme de services personnalisés, allant de la création de sites web à la mise en place de CRM, en passant par la gestion de systèmes et le développement de logiciels. Mon expertise s'étend également à la création artistique, incluant illustrations, petites animations et graphisme, pour donner vie à des idées uniques et innovantes.

Chaque projet est une occasion de fusionner esthétique et performance, afin d’offrir des solutions à la fois fonctionnelles et inspirantes. Bienvenue dans mon univers où technologie et imagination s'entrelacent pour façonner des expériences uniques."


# Team names, titles and social links
people:
- name: Philippe Depadova-Berube
  pic: 1
  position: Designer, Artiste, Technicien Informatique 
  social:
    - title: Instagram
      url: #
    - title: Linkedin
      url: #
    - title: Patreon
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Quebec
  - line: Montreal

# Build settings
markdown: kramdown
permalink: pretty
